---
# tasks file for vault (Ubuntu specific)

- name: Install libcap2-bin
  become: yes
  apt:
    name: libcap2-bin
    update_cache: yes
    state: latest
  tags:
    - vault

- name: Install unzip
  apt: name=unzip
  tags:
    - vault
