---
# handlers file for vault

- name: reload systemd
  command: systemctl daemon-reload
  tags:
    - vault

- name: restart vault
  become: yes
  service:
    name: "{{ vault_service_name }}"
    state: restarted
  tags:
    - vault

- name: reload vault
  service:
    name: "{{ vault_service_name }}"
    state: reloaded
  tags:
    - vault
